version: "3.9"

services:

  mongo:
    image: mongo
    container_name: pulse-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: pulse-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pulseHR
      - PORT=3000
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: pulse-client
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: